spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shophub
    username: root
    password: rkdmseodud930

  jpa:
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
  slack:
    webhook-uri: https://hooks.slack.com/services/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
  config: classpath:logback/logback-slack.xml

server:
  tomcat:
    basedir: tomcat

management:
  endpoints:
    enabled-by-default: false

environment: local