spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shophub
    username: root
    password: rkdmseodud930

  jpa:
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

server:
  tomcat:
    basedir: tomcat

management:
  endpoints:
    enabled-by-default: false

environment: local