name: CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up jwt yml file
        env:
          YAML_SECRET: ${{ secrets.YAML_JWT }}
          YAML_DIR: src/main/resources
          YAML_TEST_DIR: src/test/resources
          YAML_FILE_NAME: application-jwt.yml
        run: |
          echo $YAML_SECRET | base64 --decode > $YAML_DIR/$YAML_FILE_NAME
          echo $YAML_SECRET | base64 --decode > $YAML_TEST_DIR/$YAML_FILE_NAME
          echo "YAML_SECRET has been decoded and saved to $YAML_DIR/$YAML_FILE_NAME"
          echo "YAML_SECRET has been decoded and saved to $YAML_TEST_DIR/$YAML_FILE_NAME"

      - name: Set up s3 yml file
        env:
          YAML_SECRET: ${{ secrets.YAML_S3 }}
          YAML_DIR: src/main/resources
          YAML_TEST_DIR: src/test/resources
          YAML_FILE_NAME: application-s3.yml
        run: |
          echo $YAML_SECRET | base64 --decode > $YAML_DIR/$YAML_FILE_NAME
          echo $YAML_SECRET | base64 --decode > $YAML_TEST_DIR/$YAML_FILE_NAME
          echo "YAML_SECRET has been decoded and saved to $YAML_DIR/$YAML_FILE_NAME"
          echo "YAML_SECRET has been decoded and saved to $YAML_TEST_DIR/$YAML_FILE_NAME"          

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: test
        run: ./gradlew test
